# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fathom < Formula
  desc "A terminal tide dashboard powered by NOAA"
  homepage "https://github.com/mogglemoss/fathom"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.0/fathom_darwin_amd64.tar.gz"
      sha256 "e9de5c7a2466095e46ef400b200e4f2ff20d4b875688b74f9e512ae39b57146f"

      define_method(:install) do
        bin.install "fathom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.0/fathom_darwin_arm64.tar.gz"
      sha256 "96f74f1df1fcbbe8dc046c6e43db1418272d30d364ba71b36e4d71856eb35243"

      define_method(:install) do
        bin.install "fathom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.0/fathom_linux_amd64.tar.gz"
      sha256 "690c153f28eb341411a528ee7aad87515c8b1cb7d30ea949386f45dc18a32a1a"
      define_method(:install) do
        bin.install "fathom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.0/fathom_linux_arm64.tar.gz"
      sha256 "5c34ce5b7b6329672a5519e17eaba9de5e0b4abd85d0c51ad1111cb1611640e6"
      define_method(:install) do
        bin.install "fathom"
      end
    end
  end

  test do
    system "#{bin}/fathom --version"
  end
end
