# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazytailscale < Formula
  desc "A terminal dashboard for your Tailscale network"
  homepage "https://github.com/mogglemoss/lazytailscale"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v0.1.0/lazytailscale_darwin_amd64.tar.gz"
      sha256 "045d5956f026678e27dd9f2af08dbbdf4395a5b0964cc224a7532b4fdbd36e9c"

      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v0.1.0/lazytailscale_darwin_arm64.tar.gz"
      sha256 "6dd2b09caaff3640616f533149a74f5d74ac90b31d0246037fe1f4b83e72f4fd"

      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v0.1.0/lazytailscale_linux_amd64.tar.gz"
      sha256 "6a3668fa7552560cd2fa21e6d65e0490b00a35f02556ac123d0fb56a59d50bfd"
      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v0.1.0/lazytailscale_linux_arm64.tar.gz"
      sha256 "a2d1f6f435830cf13ccdcd888baaac196e15097b949327551e5c7f80713bd249"
      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazytailscale --version")
  end
end
