# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fathom < Formula
  desc "A terminal tide dashboard powered by NOAA"
  homepage "https://github.com/mogglemoss/fathom"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.1/fathom_darwin_amd64.tar.gz"
      sha256 "45bab173b8cc40293152890cd9ee7cd40750b44dfbf30268b138e91d5ccc8c50"

      define_method(:install) do
        bin.install "fathom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.1/fathom_darwin_arm64.tar.gz"
      sha256 "c36d166bd8b67ff385dc0ee2f9a161bc8b2367b1915091e1fc73f869ea07a1ae"

      define_method(:install) do
        bin.install "fathom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.1/fathom_linux_amd64.tar.gz"
      sha256 "099ce0a9434abf5c9475cf8710656a33e89216d1331c1cb1e3bd95b35ca012b8"
      define_method(:install) do
        bin.install "fathom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.1/fathom_linux_arm64.tar.gz"
      sha256 "895e8831d0a616ea3b26150668b5621a9d9923ce510b9aecb4805a6f54fdf4b4"
      define_method(:install) do
        bin.install "fathom"
      end
    end
  end

  test do
    system "#{bin}/fathom --version"
  end
end
