# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fathom < Formula
  desc "A terminal tide dashboard powered by NOAA"
  homepage "https://github.com/mogglemoss/fathom"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.2/fathom_darwin_amd64.tar.gz"
      sha256 "e87bb282865928f78e7f001fe7e2453e8f08be9f9114425a1b7e1b7e86136da2"

      define_method(:install) do
        bin.install "fathom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.2/fathom_darwin_arm64.tar.gz"
      sha256 "6d44f284a0d2a1a3e398b4a2e18b25e31728def84911ffa065a627042dc682e9"

      define_method(:install) do
        bin.install "fathom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.2/fathom_linux_amd64.tar.gz"
      sha256 "e093df939a8bac206e9e58b46fd1cf5708ea1770d72a7bf62f37c037d8a7204d"
      define_method(:install) do
        bin.install "fathom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.2/fathom_linux_arm64.tar.gz"
      sha256 "c6609f49ffff6fcc93e60f6db55b66662297b4861e37c0a1aeae4fc6be0054f9"
      define_method(:install) do
        bin.install "fathom"
      end
    end
  end

  test do
    system "#{bin}/fathom --version"
  end
end
