# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fathom < Formula
  desc "A terminal tide dashboard powered by NOAA"
  homepage "https://github.com/mogglemoss/fathom"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.3/fathom_darwin_amd64.tar.gz"
      sha256 "e28362f04c6f238c0de8db7c31b0266c4959111303bbb7d60c4d423a1dcc4e52"

      define_method(:install) do
        bin.install "fathom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.3/fathom_darwin_arm64.tar.gz"
      sha256 "fdd5f81a2cca234a8d32483e2e4efc3b53464d4be806e8fb6869a78dee23b8d7"

      define_method(:install) do
        bin.install "fathom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.3/fathom_linux_amd64.tar.gz"
      sha256 "d615cf28e233f3a5eccb3a2e19017fca7d03d6098a53c6e0695de7be2be69772"
      define_method(:install) do
        bin.install "fathom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/fathom/releases/download/v0.2.3/fathom_linux_arm64.tar.gz"
      sha256 "8eb9a6179bd8482f079cb1ebad25d3c1cfaa422ec4a016e5b8a0579269bbc558"
      define_method(:install) do
        bin.install "fathom"
      end
    end
  end

  test do
    system "#{bin}/fathom --version"
  end
end
