# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazytailscale < Formula
  desc "A terminal dashboard for your Tailscale network"
  homepage "https://github.com/mogglemoss/lazytailscale"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v1.0.2/lazytailscale_darwin_amd64.tar.gz"
      sha256 "28d6c68ffc2695294147b78b0faf52733ef49dc127c752c94f9a6e102c8df455"

      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v1.0.2/lazytailscale_darwin_arm64.tar.gz"
      sha256 "8fa8e90dcaa5867c3239863bfe39ec5c071369979c00c8fb83d4590f0fdffb36"

      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v1.0.2/lazytailscale_linux_amd64.tar.gz"
      sha256 "86e66aa87b2c1b077f4cf839d0cd30e59674ff151bb9bc261b71d3e3fcddb062"
      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v1.0.2/lazytailscale_linux_arm64.tar.gz"
      sha256 "33e9d063c2e0e9c74ca302672e8df237b9aab7902ba1dd9a48678bd9befa07f1"
      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazytailscale --version")
  end
end
