# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazytailscale < Formula
  desc "A terminal dashboard for your Tailscale network"
  homepage "https://github.com/mogglemoss/lazytailscale"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v1.1.0/lazytailscale_darwin_amd64.tar.gz"
      sha256 "2699f78fdd2c87c3f45ee48817c7e1cee149f5d85aefe35c9048866f7fd4e91c"

      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v1.1.0/lazytailscale_darwin_arm64.tar.gz"
      sha256 "1d7d1d84255c406bc5993e3e350160fca2bf7fcb15a45670b370cdc95113f487"

      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v1.1.0/lazytailscale_linux_amd64.tar.gz"
      sha256 "708ec80a66953a11e5e3578f6fcc2e32f47730082cccbae1ba7bf5a7e8528dea"
      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v1.1.0/lazytailscale_linux_arm64.tar.gz"
      sha256 "0a6912730a2d84e473ed4cec66da072147143e0c3597bcbf15fc8edfd7d29130"
      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazytailscale --version")
  end
end
