# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazytailscale < Formula
  desc "A terminal dashboard for your Tailscale network"
  homepage "https://github.com/mogglemoss/lazytailscale"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v1.0.1/lazytailscale_darwin_amd64.tar.gz"
      sha256 "b4f9337066f097bd86066227519c4371a529972af2b4954d812b1592d25d4f91"

      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v1.0.1/lazytailscale_darwin_arm64.tar.gz"
      sha256 "3c86f0ce013e32173227d47be3e5c2399d937b2a485aec2c470fefc83295733e"

      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v1.0.1/lazytailscale_linux_amd64.tar.gz"
      sha256 "4696fb89afd9e728e6087855e2d9307dc654c8a811007516f1ee9919c7300130"
      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mogglemoss/lazytailscale/releases/download/v1.0.1/lazytailscale_linux_arm64.tar.gz"
      sha256 "7a4a41d455b6ac5f9e5b54f7e2658b188dd9ffd7e6c2a5a5c065902910d2aded"
      define_method(:install) do
        bin.install "lazytailscale"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazytailscale --version")
  end
end
